### ISSUE TITLE
Error everywhere in the code; not working. Pls, Solve them and upload

### ISSUE THREAD

**Issue by jpainam** [SHI-Labs/Self-Similarity-Grouping#19]

**Comment by OasisYang** [comment]
Actually, the source train part may have some bugs, but the codes for SSG can run on my computer. I suggest you using our provided baseline model. And please do not use the functions that are not related to the main framework, since I didn't clean the codes carefully.
Also, if you meet some errors please refer to some suggestions mentioned in issues and try to solve them by yourself first.
